"use client";
import { useState } from 'react';
import { GenerateResponse } from '@/lib/types';
import CodeBlock from './CodeBlock';
import MermaidViewer from './MermaidViewer';
import { AlertCircle, Sparkles, CornerDownRight, Download, Copy, ThumbsUp, ThumbsDown } from 'lucide-react';
import { formatResultAsMarkdown, downloadTextFile } from '@/lib/utils';
import { saveFeedback } from '@/lib/storage';

interface ResultPanelProps {
  result: GenerateResponse;
  onFollowUp: (prompt: string) => void;
  isGenerating: boolean;
}

export default function ResultPanel({ result, onFollowUp, isGenerating }: ResultPanelProps) {
  const { taskType, title, content, explanation, example, mermaidCode, warnings, provider } = result;
  
  const [followUpText, setFollowUpText] = useState('');
  const [feedback, setFeedback] = useState<'helpful' | 'notHelpful' | null>(null);

  const submitFollowUp = () => {
    if (!followUpText.trim()) return;
    onFollowUp(followUpText);
    setFollowUpText('');
  };

  const handleExportTxt = () => {
    const md = formatResultAsMarkdown(result);
    // Sanitize title for filename
    const sanitizedTitle = (title || 'task_result').replace(/[\/\\?%*:|"<>]/g, '-').replace(/\s+/g, '_');
    downloadTextFile(`kdev_${sanitizedTitle}.md`, md);
  };

  const handleCopyMd = async () => {
    const md = formatResultAsMarkdown(result);
    try {
      await navigator.clipboard.writeText(md);
      alert('전체 결과가 마크다운으로 복사되었습니다.');
    } catch {
      alert('복사에 실패했습니다.');
    }
  };

  const handleFeedbackClick = (type: 'helpful' | 'notHelpful') => {
    if (feedback) return; // 한 번만 투표 가능
    saveFeedback(type);
    setFeedback(type);
  };

  return (
    <div className="mt-8 border-t border-slate-200 pt-8 animate-in fade-in duration-500">
      
      {/* 툴바 & 타이틀 영역 */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between mb-6 gap-4">
        <div className="flex items-center gap-3">
          {title && <h2 className="text-xl font-bold text-slate-800">{title}</h2>}
          {provider && (
            <div className="flex items-center gap-1 px-2 py-1 bg-purple-50 text-purple-700 text-xs font-semibold rounded-full border border-purple-100">
              <Sparkles className="w-3 h-3" />
              Generated by {provider.toUpperCase()}
            </div>
          )}
        </div>
        
        {/* 내보내기 액션 */}
        <div className="flex gap-2">
          <button
            onClick={handleCopyMd}
            className="flex items-center gap-1 px-3 py-1.5 bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 text-xs font-bold rounded-md transition-colors"
          >
            <Copy className="w-3.5 h-3.5" />
            MD 복사
          </button>
          <button
            onClick={handleExportTxt}
            className="flex items-center gap-1 px-3 py-1.5 bg-white border border-slate-200 hover:bg-slate-50 text-slate-600 text-xs font-bold rounded-md transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            파일 다운로드
          </button>
        </div>
      </div>
      
      {warnings && warnings.length > 0 && (
        <div className="mb-6 p-4 bg-amber-50 border-l-4 border-amber-500 text-amber-800 rounded-r-md flex gap-3">
          <AlertCircle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <h4 className="font-bold flex items-center mb-1">주의사항</h4>
            <ul className="list-disc ml-5 space-y-1 text-sm">
              {warnings.map((warn, i) => (
                <li key={i}>{warn}</li>
              ))}
            </ul>
          </div>
        </div>
      )}

      <div className="space-y-8">
        {/* 순서도 */}
        {taskType === 'flow' && (
          <>
            {mermaidCode && (
              <section>
                <h3 className="text-lg font-semibold text-slate-800 mb-3">프로세스 시각화</h3>
                <MermaidViewer chart={mermaidCode} />
              </section>
            )}
            
            {content && (
              <section>
                <h3 className="text-lg font-semibold text-slate-800 mb-3">프로세스 요약</h3>
                <div className="text-sm text-slate-700 bg-white p-5 border border-slate-200 rounded-md shadow-sm whitespace-pre-wrap leading-relaxed">
                  {content}
                </div>
              </section>
            )}

            {explanation && (
              <section>
                <h3 className="text-lg font-semibold text-slate-800 mb-3">상세 설명</h3>
                <div className="text-sm text-slate-600 bg-blue-50 p-5 rounded-md border border-blue-100 whitespace-pre-wrap leading-relaxed">
                  {explanation}
                </div>
              </section>
            )}
          </>
        )}

        {/* SQL & TS */}
        {taskType !== 'flow' && (
          <>
            {explanation && (
              <section className="bg-slate-50 p-5 rounded-md border border-slate-100 text-slate-700 leading-relaxed whitespace-pre-wrap">
                <h3 className="text-sm font-bold text-slate-900 mb-2 uppercase tracking-wider">Explanation</h3>
                {explanation}
              </section>
            )}

            {content && (
              <section>
                <h3 className="text-lg font-semibold text-slate-800 mb-3">
                  {taskType === 'sql' ? 'SQL 코드' : 'TypeScript 구현'}
                </h3>
                <CodeBlock code={content} language={taskType === 'sql' ? 'sql' : 'typescript'} />
              </section>
            )}

            {example && (
              <section>
                <h3 className="text-lg font-semibold text-slate-800 mb-3">사용 예시</h3>
                <CodeBlock code={example} language={taskType === 'sql' ? 'sql' : 'typescript'} />
              </section>
            )}
          </>
        )}
      </div>

      {/* 품질 피드백 영역 */}
      <div className="flex items-center justify-center gap-4 mt-10 pt-6 border-t border-slate-100">
        <span className="text-sm text-slate-500 font-medium">이 결과물이 실무에 도움이 되었나요?</span>
        <div className="flex gap-2">
          <button
            onClick={() => handleFeedbackClick('helpful')}
            disabled={feedback !== null}
            className={`p-2 rounded-full transition-colors ${
              feedback === 'helpful' 
                ? 'bg-blue-100 text-blue-600' : 
              feedback === 'notHelpful' ? 'opacity-30' : 'bg-slate-100 hover:bg-slate-200 text-slate-600'
            }`}
            title="유용함"
          >
            <ThumbsUp className="w-4 h-4" />
          </button>
          <button
            onClick={() => handleFeedbackClick('notHelpful')}
            disabled={feedback !== null}
            className={`p-2 rounded-full transition-colors ${
              feedback === 'notHelpful' 
                ? 'bg-red-100 text-red-600' : 
              feedback === 'helpful' ? 'opacity-30' : 'bg-slate-100 hover:bg-slate-200 text-slate-600'
            }`}
            title="아쉬움"
          >
            <ThumbsDown className="w-4 h-4" />
          </button>
        </div>
        {feedback && <span className="text-xs text-slate-400">의견이 등록되었습니다.</span>}
      </div>

      {/* 후속 수정 요청 입력창 */}
      <div className="mt-6 bg-slate-100 p-5 rounded-lg border border-slate-200">
        <label className="flex items-center gap-2 text-sm font-bold text-slate-800 mb-3">
          <CornerDownRight className="w-4 h-4 text-slate-500" />
          결과가 마음에 들지 않나요? 추가 수정을 요청하세요.
        </label>
        <div className="flex gap-2">
          <input
            type="text"
            value={followUpText}
            onChange={(e) => setFollowUpText(e.target.value)}
            disabled={isGenerating}
            onKeyDown={(e) => {
              if (e.key === 'Enter') submitFollowUp();
            }}
            placeholder="예시) Oracle용으로 변경해줘, 타입스크립트 제네릭을 적용해줘..."
            className="flex-1 px-4 py-2 text-sm border border-slate-300 rounded-md focus:ring-2 focus:ring-blue-500 outline-none disabled:opacity-50"
          />
          <button
            onClick={submitFollowUp}
            disabled={isGenerating || !followUpText.trim()}
            className="px-6 py-2 bg-slate-800 text-white text-sm font-bold rounded-md hover:bg-slate-900 transition-colors disabled:opacity-50"
          >
            수정 생성
          </button>
        </div>
      </div>
    </div>
  );
}
